### ISSUE TITLE
onRuntimeInitialized is never called

### ISSUE THREAD

**Issue by bartbutenaers** [chafey/charls-js#3]
Hello Chris (@chafey),

Not sure if you can help me, because if I am not mistaken you have not yet published this package on npm.  But instead I have installed the [@cornerstonejs/codec-charls](https://www.npmjs.com/package/@cornerstonejs/codec-charls) which points to your repository...

But hopefully you can still see what I am doing wrong.  Must be something stupid (I hope).

When I do this:
```
const charlsJs = require('@cornerstonejs/codec-charls');
charlsJs.onRuntimeInitialized = async _ => {
   // My custom code
}
```

Then the `onRuntimeInitialized` is never called :-(

P.S. I am using NodeJs version v12.19.0.

Thanks in advance !!!
Bart Butenaers

**Comment by bartbutenaers** [comment]
Ok, seemed that the `require` statements returns a function, so I had to add `()` to call it:
```
const charlsJs = require('@cornerstonejs/codec-charls')();
```
So that is solved.
But stuck again...  When I call this:
```
decoder.decode();
```
Then I get the exception that I should pass 0 arguments to this function, instead of 0 arguments.  So not sure what that is about.  That exception is raised here:

![image](https://user-images.githubusercontent.com/14224149/148643567-a9d18151-f958-4387-b00d-be68206ba9a5.png)

Thanks!

**Comment by chafey** [comment]
Hi Bart - I don’t know off the top of my head, did you try out the node example in this repo:

https://github.com/chafey/charls-js/blob/master/test/node/index.js

**Comment by bartbutenaers** [comment]
Hey Chris,
Thanks for your fast response!
Yes indeed I used that example to start with this library:
```
// ' buffer' contains my jpeg encoded image
var decoder = new charlsJs.JpegLSDecoder();
var decoderBuffer = decoder.getEncodedBuffer(buffer.length);
decoderBuffer.set(buffer);
decoder.decode();
```
I have debugged this over and over and over again, but don't see what I am doing wrong.
The `decode` method expects zero parameters:

![image](https://user-images.githubusercontent.com/14224149/148660009-516a9e56-3d8b-4871-b6e6-b548941007fe.png)

And I pass zero arguments,  I still i keep getting that error...
Moreover I am getting nuts: since `arguments length` is `0`, how on earth can I arrive within the `if(arguments.length !== 0) condition`.  Don't see what is wrong...

**Comment by chafey** [comment]
Any update on this issue?  One possible cause of this is the node version you are using.  I just ran it on my mac using Node v16.3.0:
√ node (master) % npm run test

> node@1.0.0 test
> node index.js

Decode of ../fixtures/jls/CT1.JLS took 5.369811 ms
  frameInfo =  { width: 512, height: 512, bitsPerSample: 16, componentCount: 1 }
  decoded length =  524288
Decode of ../fixtures/jls/CT2.JLS took 5.340883 ms
  frameInfo =  { width: 512, height: 512, bitsPerSample: 16, componentCount: 1 }
  decoded length =  524288
Decode of ../../extern/charls/test/lena8b.jls took 6.267212000000001 ms
  frameInfo =  { width: 512, height: 512, bitsPerSample: 8, componentCount: 1 }
  decoded length =  262144
Encode of ../fixtures/raw/CT2.RAW took 6.631587000000001 ms
  encoded length= 115504
√ node (master) % node --version
v16.13.0

**Comment by bartbutenaers** [comment]
Hi @chafey,

Sorry for the delay.  Long (unplanned) hours this week at work.
Yes indeed your test works fine here:

![image](https://user-images.githubusercontent.com/14224149/149195446-c15e28fc-6751-464d-ab28-66e05d8676fd.png)

And the speed is quite impressive!!
So it won't be my older NodeJs version I assume.
But of course I tested your repo, which I downloaded via a `git clone`.
However I need an npm package (which I can use as a dependency), so I need to get it working via the '@cornerstonejs/codec-charls package.

I will need to do some more tests.  Will keep you updated.  
If you have any other tips or things that I could try, don't hesitate to let me know.  All help is welcome!

**Comment by chafey** [comment]
I don't know what is different about the cornerstonejs/codec-charls package (it was based on this repo but I didn't create it) - did you try posting an issue there?  If you can't get it to working, you can always use git submodule to reference this repo

**Comment by bartbutenaers** [comment]
The weird thing is that the npm [module](https://www.npmjs.com/package/@cornerstonejs/codec-charls) shows links to your repository:

![image](https://user-images.githubusercontent.com/14224149/149198459-2dee7803-e4b9-4189-8e75-8b7c59566e4d.png)

So I thought that your perhaps somehow were working together...

And I also assumed that he just published your repo, without any changes.
Because when I do this:
```
require.resolve('@cornerstonejs/codec-charls')
```
I get this result:
'C:\\Users\\Gebruiker\\.node-red\\node_modules\\@cornerstonejs\\codec-charls\\dist\\charlsjs.js'
So it seemed to me that he used the same charlsjs.js file as in your example above.
But perhaps not...

**Comment by chafey** [comment]
That is weird - I am guessing just an error when they copied the code over.  I was certainly aware of the effort but did not work on it

**Comment by bartbutenaers** [comment]
Ok I have tried to narrow down the problem a bit more.

1. I download [this](https://upload.wikimedia.org/wikipedia/commons/b/b3/Team_Queerala.jpg) example image (which I had choosen randomly last week) to a file.

2. I change your index.js test to load this file:

   ```
   decode('C:\\temp\\Team_Queerala.jpg');
   ```

3. Then I run your example:
   ```
   node --trace_uncaught C:\Users\Gebruiker\charls-js\test\node\index.js
   ```

4. Which shows the decoding exception (which is a number?):
   ```
   5671952
   Thrown at:
       at C:\Users\Gebruiker\charls-js\dist\charlsjs.js:1:1852
       at emit (events.js:314:20)
       at internal/process/execution.js:165:25
   ```

I don't see anything wrong with that jpeg image.  Hopefully it makes more sense to you...

**Comment by chafey** [comment]
This library is for decoding JPEG-LS images.  The image you linked is JPEG baseline (different).  What are you trying to do...?

**Comment by bartbutenaers** [comment]
Oh what a mistake then ;-(
To be honest, I have never thought about the fact that there are multiple types of jpegs...
I am a contributor for the open source Node-RED IOT dataflow framework.
Would like to create two nodes (as you can see in the screenshots in [this](https://discourse.nodered.org/t/best-way-to-handle-raw-image-data-in-node-red/56424?u=bartbutenaers) discussion): one for decoding jpeg images from IP camera's, and another one for encoding jpeg images.
Pure javascript is too slow, and nativie libraries give a lot of build headaches on various platforms.  So wanted to try whether wasm was fast enough...

**Comment by bartbutenaers** [comment]
Apologies for the confusion, and for wasting your precious time!!!
I will close this issue and look for another library.
Thanks a lot and keep up the good work!!
